// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYre4QTFAdoprXFFZFkxKIbLybkigFQVY',
    appId: '1:186860742849:web:d1f20de5909a684a530c40',
    messagingSenderId: '186860742849',
    projectId: 'to-do-a7722',
    authDomain: 'to-do-a7722.firebaseapp.com',
    databaseURL: 'https://to-do-a7722-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-a7722.firebasestorage.app',
    measurementId: 'G-47QNXMZR5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIIipgdDhZ9KFeJW4ZgzT4uou_gtwxj70',
    appId: '1:186860742849:android:068d78dbc8c2997a530c40',
    messagingSenderId: '186860742849',
    projectId: 'to-do-a7722',
    databaseURL: 'https://to-do-a7722-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-a7722.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh7qBVe0TABfZe65juC-snlYvRUdKAt_A',
    appId: '1:186860742849:ios:3bc371e0d1983c1c530c40',
    messagingSenderId: '186860742849',
    projectId: 'to-do-a7722',
    databaseURL: 'https://to-do-a7722-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-a7722.firebasestorage.app',
    iosBundleId: 'com.spiderwebarts.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh7qBVe0TABfZe65juC-snlYvRUdKAt_A',
    appId: '1:186860742849:ios:0f7b34878e1e9858530c40',
    messagingSenderId: '186860742849',
    projectId: 'to-do-a7722',
    databaseURL: 'https://to-do-a7722-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-a7722.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYre4QTFAdoprXFFZFkxKIbLybkigFQVY',
    appId: '1:186860742849:web:0a2acded1aacc851530c40',
    messagingSenderId: '186860742849',
    projectId: 'to-do-a7722',
    authDomain: 'to-do-a7722.firebaseapp.com',
    databaseURL: 'https://to-do-a7722-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-a7722.firebasestorage.app',
    measurementId: 'G-226FM7MP97',
  );

}